### ISSUE TITLE
Fake users to represent Creator Curators

### ISSUE THREAD

**Issue by StarflightGamin** [LittleBigRefresh/Refresh#455] opened 2024-05-04 06:04 UTC
Maybe we could make fake users to represent creator curators and have their uploaded levels be the respective story levels? That could solve the "Story Level #####" issue, and also make it so you can view the leaderboards on those levels. They could even have some sort of badge to mark them as story worlds on Refresh (plus the option to heart them could be removed)

**Comment by jvyden** [comment] 2024-05-04 06:10
This wouldn't solve the issue at hand and would probably just create more chaos. Story levels are handled weirdly enough internally.

We plan to import the translation keys as a part of #196 which will allow the level titles to match. We just haven't gotten around to it as it hasn't been a priority.

Duplicate of #196.

**Closed by jvyden** 2024-05-04 06:10 UTC

**Comment by StarflightGamin** [comment] 2024-05-04 06:11
Yea that makes sense lol
