### ISSUE TITLE
Uploading Level/Profile Icons via website?

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#311] opened 2023-12-31 20:28 UTC
In a similar vein to lighthouse, let Refresh users upload level and profile icons from the comfort of their own Personal Computer

these pictures would be downsized and cropped to 512x512 and the user should be able to crop which specific part of the image is applied as the icon

**Comment by Beyley** [comment] 2023-12-31 20:30
This will be especially helpful for PSP, where the only known way to get custom level badges is through a custom server.

**Comment by jvyden** [comment] 2023-12-31 22:33
This is technically already possible through Refresh's API, but it lacks support in refresh-web. Closing as duplicate of https://github.com/LittleBigRefresh/refresh-web/issues/34.

**Closed by jvyden** 2023-12-31 22:33 UTC

**Comment by Beyley** [comment] 2023-12-31 22:38
> This is technically already possible through Refresh's API, but it lacks support in refresh-web. Closing as duplicate of [LittleBigRefresh/refresh-web#34](https://github.com/LittleBigRefresh/refresh-web/issues/34).

Does the current API cover the case of converting from PNG to some other format? LBP PSP cant read PNG files, and we must convert to MIP, how should we handle that in the API? If the API doesnt cover it, we should probably open an issue about figuring out an API structure for LBP PSP image conversion

**Comment by jvyden** [comment] 2023-12-31 22:40
That case would never be handled by the API - that should be done by mapping asset hashes to those of PNG files. It's an issue in the same vein as #309 IMO

**Comment by Beyley** [comment] 2023-12-31 22:41
I'll convert that issue into a general asset hash mapping issue, since its scope extends to PSP, Vita, and PS3

**Comment by jvyden** [comment] 2023-12-31 22:42
Too late ;)
