### ISSUE TITLE
Players playing LBP1 do not show up in player count

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#399] opened 2024-04-14 15:00 UTC
Even if a player is connected to the game, the game will not put the player in any room and it will appear as if there was nobody playing in the first place

this screenshot was taken at the time where TWO users were playing on LBP1, it's truly mind-boggling
![image](https://github.com/LittleBigRefresh/Refresh/assets/93880348/eb47fcca-d3e8-468c-8dc8-35cfaf7e995e)

**Comment by Beyley** [comment] 2024-04-14 18:49
duplicate of #147 im pretty sure

**Closed by Beyley** 2024-04-14 18:49 UTC
